brandingAppName: Quanta
brandingMetaContent: "Quanta: Social Media Micro-blogging Platform for the Fediverse!"

# Tip: This 'menu' property is seen in TypeScript JSON as an array of objects in 
# variable 'S.quanta.config'
#
# Links here can be full url, or node names, or "tab:tabName"

rhsAnonLinks:
  - name: "About Quanta"
    link: ":home"
  - name: "Explore Features"
    link: ":features"

# These links will show up under MAIN section
# rhsLinks:
#   - name: "separator"
#     link: ""
#   - name: "News"
#     link: ":quanta-news"

systemFolderLinks:
  - name: "User Guide"
    link: ":user-guide"
  - name: "Portal Home"
    link: ":home"

rhsFeedLinks:
  - name: "separator"
    link: ""
  - name: "News"
    link: ":quanta-news"

menu:
  help:
    - name: "About Quanta"
      link: ":home"
    - name: "User Guide"
      link: ":user-guide"

# NOTE: These entries have an interface in the typescript called 'ConfigProp' in 'interfaces.ts'
props:
  Person:
    givenName:
      label: "First Name"
      width: 40
    familyName:
      label: "Last Name"
      width: 60
    jobTitle:
      label: "Job Title"
      width: 50
    worksFor:
      label: "Company"
      width: 50
    email:
      label: "Email"
      width: 50
    telephone:
      label: "Telephone"
      width: 50
    address:
      label: "Address"
      width: 100
    birthDate:
      label: "Birthday"
      width: 100
      showTime: false
      